/*
 * File: app/view/Activities.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.view.Activities', {
    extend: 'Ext.dataview.List',
    alias: 'widget.activities',

    requires: [
        'Ext.Msg.alert'
    ],

    config: {
        itemId: 'activities',
        store: 'activities',
        onItemDisclosure: false,
        itemTpl: [
            '<div>{type}</div>'
        ],
        items: [
            {
                xtype: 'container',
                docked: 'top',
                html: 'Select your current activity (hold item for definition).',
                padding: 10,
                style: 'background: #EDEBF1; color: #555; font-size: 0.9em;'
            }
        ]
    }

});