/*
 * File: app/view/MyPicker.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.view.MyPicker', {
    extend: 'Ext.picker.Picker',

    config: {
        cancelButton: {
            itemId: 'mybutton12'
        },
        slots: [
            {
                xtype: 'pickerslot',
                data: [
                    {
                        text: 'One',
                        value: 1
                    },
                    {
                        text: 'Two',
                        value: 2
                    },
                    {
                        text: 'Three',
                        value: 3
                    }
                ],
                name: 'MyPickerSlot3',
                title: 'MyPickerSlot3'
            }
        ],
        toolbar: {
            xtype: 'toolbar',
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    text: 'Clear'
                }
            ]
        },
        listeners: [
            {
                fn: 'onMybutton12Tap',
                event: 'tap',
                delegate: '#mybutton12'
            }
        ]
    },

    onMybutton12Tap: function(button, e, eOpts) {

    }

});