/*
 * File: app/view/Pending.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.view.Pending', {
    extend: 'Ext.Container',

    config: {
        itemId: 'pending',
        padding: 20,
        items: [
            {
                xtype: 'container',
                html: 'TAWKS',
                style: 'font-size: 250%'
            },
            {
                xtype: 'container',
                html: '<b>Registration pending.</b>  If you do not receive a text message, check your registration settings.  Otherwise you may close this window.'
            },
            {
                xtype: 'button',
                margin: '10 30 10 30',
                ui: 'back',
                text: 'Registration Settings'
            },
            {
                xtype: 'button',
                text: 'Contact Administrator	'
            }
        ]
    }

});