/*
 * File: app/view/Playground.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.view.Playground', {
    extend: 'Ext.Container',

    config: {
        html: '<p>TAWKS was designed primarly for mobile devices. To scroll to the bottom on a desktop computer you must click and hold the mouse button to mimic a touch and move the cursor up and down. </p><br/><p>Try to scrolling to read the message below.</p><p style="margin-top: 1500px">Welcome to TAWKS!  You may now close this window.</p>',
        itemId: 'playground',
        padding: 20,
        style: 'font-size: 1.5em;',
        scrollable: 'vertical'
    }

});