/*
 * File: app/view/Register.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.view.Register', {
    extend: 'Ext.form.Panel',
    alias: 'widget.register',

    config: {
        itemId: 'register',
        layout: {
            type: 'vbox'
        },
        scrollable: true,
        items: [
            {
                xtype: 'fieldset',
                title: 'Personal Info',
                items: [
                    {
                        xtype: 'emailfield',
                        disabled: true,
                        itemId: 'email',
                        name: 'Email',
                        placeHolder: 'email@example.com',
                        listeners: [
                            {
                                fn: function(component, eOpts) {
                                    var main = Ext.getCmp('main');

                                    component.setValue(main.Email);
                                },
                                event: 'initialize'
                            }
                        ]
                    },
                    {
                        xtype: 'hiddenfield',
                        itemId: 'userName',
                        name: 'UserName',
                        listeners: [
                            {
                                fn: function(component, eOpts) {
                                    var main = Ext.getCmp('main');

                                    component.setValue(main.UserName);
                                },
                                event: 'initialize'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Phone',
                items: [
                    {
                        xtype: 'selectfield',
                        name: 'carrier',
                        placeHolder: 'Select Your Carrier',
                        autoSelect: false,
                        options: [
                            {
                                text: 'Verizon',
                                value: '@vtext.com'
                            },
                            {
                                text: 'AT&T',
                                value: '@txt.att.net'
                            },
                            {
                                text: 'T-Mobile',
                                value: '@tmomail.net'
                            },
                            {
                                text: 'Sprint',
                                value: '@messaging.sprintpcs.com'
                            }
                        ]
                    },
                    {
                        xtype: 'textfield',
                        component: {
                            xtype: 'input',
                            type: 'tel',
                            fastFocus: true
                        },
                        name: 'phone',
                        placeHolder: '10-Digit Phone Number'
                    }
                ]
            },
            {
                xtype: 'container',
                html: 'Please enter your hours of availability below.  Leave start and end times empty on the days you don\'t want to be contacted.',
                margin: '10 0 -15 0',
                padding: 10
            },
            {
                xtype: 'fieldset',
                itemId: 'myfieldset2',
                title: 'Monday',
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            component.add(Tawks.app.createPickers('monday'));
                        },
                        event: 'initialize'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'myfieldset3',
                title: 'Tuesday',
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            component.add(component.add(Tawks.app.createPickers('tuesday')));
                        },
                        event: 'initialize'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'myfieldset4',
                title: 'Wednesday',
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            component.add(component.add(Tawks.app.createPickers('wednesday')));
                        },
                        event: 'initialize'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'myfieldset5',
                title: 'Thursday',
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            component.add(component.add(Tawks.app.createPickers('thursday')));
                        },
                        event: 'initialize'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'myfieldset6',
                title: 'Friday',
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            component.add(component.add(Tawks.app.createPickers('friday')));
                        },
                        event: 'initialize'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'myfieldset7',
                title: 'Saturday',
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            component.add(component.add(Tawks.app.createPickers('saturday')));
                        },
                        event: 'initialize'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'myfieldset8',
                title: 'Sunday',
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            component.add(component.add(Tawks.app.createPickers('sunday')));
                        },
                        event: 'initialize'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'myfieldset9',
                title: 'What time would you like to receive your end <br />of the day question?',
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            component.add({
                                xtype: 'datetimepickerfield',
                                name : 'endDayQuestionTime',
                                value: new Date(),
                                placeHolder: 'Time',
                                clearIcon: true,
                                dateTimeFormat : 'h:i:A',
                                autoSelect: false,
                                picker: {
                                    yearFrom: 1980,
                                    minuteInterval : 1,
                                    ampm : true,
                                    slotOrder: ['hour','minute','ampm']
                                }
                            });
                        },
                        event: 'initialize'
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'register',
                margin: '10 30 10 30',
                text: 'Register'
            },
            {
                xtype: 'textfield',
                label: 'Field'
            }
        ]
    },

    onTextfieldFocus: function(textfield, e, eOpts) {

    }

});