/*
 * File: app/view/Register.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.view.Register', {
    extend: 'Ext.form.Panel',
    alias: 'widget.register',

    requires: [
        'Tawks.form.NumberInput'
    ],

    config: {
        itemId: 'register',
        layout: {
            type: 'vbox'
        },
        scrollable: true,
        items: [
            {
                xtype: 'button',
                hidden: true,
                itemId: 'quit',
                margin: '10 30 10 30',
                ui: 'decline',
                text: 'Withdraw from TAWKS Study'
            },
            {
                xtype: 'fieldset',
                title: 'Personal Info',
                items: [
                    {
                        xtype: 'emailfield',
                        disabled: true,
                        itemId: 'email',
                        name: 'Email',
                        placeHolder: 'email@example.com',
                        listeners: [
                            {
                                fn: function(component, eOpts) {
                                    var main = Ext.getCmp('main');

                                    component.setValue(main.Email);
                                },
                                event: 'initialize'
                            }
                        ]
                    },
                    {
                        xtype: 'hiddenfield',
                        itemId: 'userName',
                        name: 'UserName',
                        listeners: [
                            {
                                fn: function(component, eOpts) {
                                    var main = Ext.getCmp('main');

                                    component.setValue(main.UserName);
                                },
                                event: 'initialize'
                            }
                        ]
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'gender',
                        label: '',
                        name: 'gender',
                        placeHolder: 'What is your gender?',
                        autoSelect: false,
                        options: [
                            {
                                text: 'Female',
                                value: 'Female'
                            },
                            {
                                text: 'Male',
                                value: 'Male'
                            }
                        ]
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'rank',
                        label: '',
                        name: 'rank',
                        placeHolder: 'What is your academic rank?',
                        autoSelect: false,
                        options: [
                            {
                                text: 'Professor',
                                value: 'Professor'
                            },
                            {
                                text: 'Associate Professor',
                                value: 'Associate Professor'
                            },
                            {
                                text: 'Assistant Professor',
                                value: 'Assistant Professor'
                            },
                            {
                                text: 'Lecturer',
                                value: 'Lecturer'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Do you have a formal paid administrative <br />responsibility within the University?',
                items: [
                    {
                        xtype: 'radiofield',
                        label: 'Yes',
                        name: 'paidResponsibility',
                        value: 'yes'
                    },
                    {
                        xtype: 'radiofield',
                        label: 'No',
                        name: 'paidResponsibility',
                        value: 'no'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'phoneSet',
                title: 'Phone',
                items: [
                    {
                        xtype: 'selectfield',
                        name: 'carrier',
                        placeHolder: 'Select Your Carrier',
                        autoSelect: false,
                        options: [
                            {
                                text: 'Verizon',
                                value: '@vtext.com'
                            },
                            {
                                text: 'AT&T',
                                value: '@txt.att.net'
                            },
                            {
                                text: 'T-Mobile',
                                value: '@tmomail.net'
                            },
                            {
                                text: 'Sprint',
                                value: '@messaging.sprintpcs.com'
                            }
                        ]
                    }
                ],
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            // This adds a special input component that only accepts numbers as input...
                            component.add({xtype: 'numberinput', placeHolder: 'Enter Phone Number', name: 'phone'});
                        },
                        event: 'initialize'
                    }
                ]
            },
            {
                xtype: 'container',
                html: 'What are the hours of the day within which you typically work?<br/><br/><span style="font-size: 80%">Tap, "Turn Off" on the days you don\'t want to be contacted.</span>',
                margin: '10 0 -15 0',
                padding: 10
            },
            {
                xtype: 'fieldset',
                itemId: 'myfieldset2',
                title: 'Monday',
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            component.add(Tawks.app.createPickers('monday'));
                        },
                        event: 'initialize'
                    }
                ],
                items: [
                    {
                        xtype: 'button',
                        day: 'monday',
                        hidden: false,
                        itemId: 'dayToggleButton',
                        margin: '20 10 0 0',
                        style: 'float: right;',
                        ui: 'action',
                        width: 80,
                        text: 'Turn Off'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'myfieldset3',
                title: 'Tuesday',
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            component.add(component.add(Tawks.app.createPickers('tuesday')));
                        },
                        event: 'initialize'
                    }
                ],
                items: [
                    {
                        xtype: 'button',
                        day: 'monday',
                        hidden: false,
                        itemId: 'dayToggleButton1',
                        margin: '20 10 0 0',
                        style: 'float: right;',
                        ui: 'action',
                        width: 80,
                        text: 'Turn Off'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'myfieldset4',
                title: 'Wednesday',
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            component.add(component.add(Tawks.app.createPickers('wednesday')));
                        },
                        event: 'initialize'
                    }
                ],
                items: [
                    {
                        xtype: 'button',
                        day: 'monday',
                        hidden: false,
                        itemId: 'dayToggleButton2',
                        margin: '20 10 0 0',
                        style: 'float: right;',
                        ui: 'action',
                        width: 80,
                        text: 'Turn Off'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'myfieldset5',
                title: 'Thursday',
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            component.add(component.add(Tawks.app.createPickers('thursday')));
                        },
                        event: 'initialize'
                    }
                ],
                items: [
                    {
                        xtype: 'button',
                        day: 'monday',
                        hidden: false,
                        itemId: 'dayToggleButton3',
                        margin: '20 10 0 0',
                        style: 'float: right;',
                        ui: 'action',
                        width: 80,
                        text: 'Turn Off'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'myfieldset6',
                title: 'Friday',
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            component.add(component.add(Tawks.app.createPickers('friday')));
                        },
                        event: 'initialize'
                    }
                ],
                items: [
                    {
                        xtype: 'button',
                        day: 'monday',
                        hidden: false,
                        itemId: 'dayToggleButton4',
                        margin: '20 10 0 0',
                        style: 'float: right;',
                        ui: 'action',
                        width: 80,
                        text: 'Turn Off'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'myfieldset7',
                title: 'Saturday',
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            component.add(component.add(Tawks.app.createPickers('saturday')));
                        },
                        event: 'initialize'
                    }
                ],
                items: [
                    {
                        xtype: 'button',
                        day: 'monday',
                        hidden: false,
                        itemId: 'dayToggleButton5',
                        margin: '20 10 0 0',
                        style: 'float: right;',
                        ui: 'action',
                        width: 80,
                        text: 'Turn Off'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'myfieldset8',
                title: 'Sunday',
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            component.add(component.add(Tawks.app.createPickers('sunday')));
                        },
                        event: 'initialize'
                    }
                ],
                items: [
                    {
                        xtype: 'button',
                        day: 'monday',
                        hidden: false,
                        itemId: 'dayToggleButton6',
                        margin: '20 10 0 0',
                        style: 'float: right;',
                        ui: 'action',
                        width: 80,
                        text: 'Turn Off'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'myfieldset9',
                title: 'At what time of the day do you wish to receive<br /> your end of the day question about your <br />satisfaction with your day\'s productivity?',
                listeners: [
                    {
                        fn: function(component, eOpts) {

                            component.add({
                                xtype: 'datetimepickerfield',
                                name : 'endDayQuestionTime',
                                value: new Date('1 Jan, 2010 17:00:00'),
                                placeHolder: 'Time',
                                clearIcon: true,
                                dateTimeFormat : 'h:i:A',
                                autoSelect: false,
                                picker: {
                                    yearFrom: 1980,
                                    minuteInterval : 1,
                                    ampm : true,
                                    slotOrder: ['hour','minute','ampm']
                                }
                            });
                        },
                        event: 'initialize'
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'registerButton',
                margin: '10 30 10 30',
                text: 'Register'
            }
        ],
        listeners: [
            {
                fn: 'onQuitTap',
                event: 'tap',
                delegate: '#quit'
            },
            {
                fn: 'onDayToggleButtonTap',
                event: 'tap',
                delegate: '#dayToggleButton'
            },
            {
                fn: 'onDayToggleButtonTap1',
                event: 'tap',
                delegate: '#dayToggleButton1'
            },
            {
                fn: 'onDayToggleButtonTap11',
                event: 'tap',
                delegate: '#dayToggleButton2'
            },
            {
                fn: 'onDayToggleButtonTap111',
                event: 'tap',
                delegate: '#dayToggleButton3'
            },
            {
                fn: 'onDayToggleButtonTap1111',
                event: 'tap',
                delegate: '#dayToggleButton4'
            },
            {
                fn: 'onDayToggleButtonTap11111',
                event: 'tap',
                delegate: '#dayToggleButton5'
            },
            {
                fn: 'onDayToggleButtonTap111111',
                event: 'tap',
                delegate: '#dayToggleButton6'
            }
        ]
    },

    onQuitTap: function(button, e, eOpts) {
        var register = Ext.ComponentQuery.query('#register')[0];

        register.setMasked({xtype: 'loadmask'});
        Ext.Msg.confirm('Delete Account', 
        'Are you sure you want to quit TAWKS? All your data will be deleted.', 
        function(buttonText) {

            if(buttonText === "yes") {

                Ext.Ajax.request({
                    url: 'https://dev-web.boisestate.edu/tawks/account/quit',
                    success: function(response) {
                        register.setMasked(false);

                        Tawks.app.redirectTo('login');
                    },
                    failure: function() {
                        alert('something went wrong.');
                        register.setMasked(false);
                    }

                });

            }
        });
    },

    onDayToggleButtonTap: function(button, e, eOpts) {
        this.toggleDay(button, 'monday');
    },

    onDayToggleButtonTap1: function(button, e, eOpts) {
        this.toggleDay(button, 'tuesday');
    },

    onDayToggleButtonTap11: function(button, e, eOpts) {
        this.toggleDay(button, 'wednesday');
    },

    onDayToggleButtonTap111: function(button, e, eOpts) {
        this.toggleDay(button, 'thursday');
    },

    onDayToggleButtonTap1111: function(button, e, eOpts) {
        this.toggleDay(button, 'friday');
    },

    onDayToggleButtonTap11111: function(button, e, eOpts) {
        this.toggleDay(button, 'saturday');
    },

    onDayToggleButtonTap111111: function(button, e, eOpts) {
        this.toggleDay(button, 'sunday');
    },

    toggleDay: function(button, day) {
        var start = Ext.ComponentQuery.query('#'+day+'StartTime')[0],
            end   = Ext.ComponentQuery.query('#'+day+'EndTime')[0],
            morn = new Date('1 Jan, 2010 08:00:00'),
            night = new Date('1 Jan, 2010 23:00:00');


        //console.log(button.config.off);
        if(button.getText() === "Turn On") {
            button.setText('Turn Off');
            button.setUi('action');

            start.setDisabled(false);
            start.setValue(morn);
            end.setDisabled(false);
            end.setValue(night);


        } else {

            //console.log('on');
            button.setText('Turn On');
            button.setUi('confirm');

            start.setValue('');
            start.setDisabled(true);
            end.setValue('');
            end.setDisabled(true);

            //console.log(button.config.off);
        }

        //console.log(start.getDisabled());
    }

});