/*
 * File: app/view/Start.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.view.Start', {
    extend: 'Ext.Container',
    alias: 'widget.start',

    config: {
        itemId: 'start',
        layout: {
            type: 'vbox'
        },
        scrollable: 'vertical',
        items: [
            {
                xtype: 'container',
                html: '<div style="font-size: 1.2em;"><b>Time Allocation Workload Knowledge Study (TAWKS): Phase 2</div><br/>  Consent Statement</b>',
                padding: 10
            },
            {
                xtype: 'container',
                html: 'Please consider this information carefully before deciding whether to participate in this research.',
                itemId: 'mycontainer',
                padding: 10
            },
            {
                xtype: 'container',
                html: '<b>Purpose of the research:</b> To develop empirical data on faculty workload and productivity.',
                padding: 10
            },
            {
                xtype: 'container',
                html: '<b>What you will do in this research:</b> You will first provide some general information  about how best to contact you for this study. Each day you will receive several randomly   generated text notifications that will provide you a link to a webpage on your mobile device   where you will report what you were doing, with whom, and where. You will decide when   you want to be notified. At the end of each day (again you will decide at what time) you   will receive a special notification with a link to a webpage that will provide you a scale to  measure your level of satisfaction with that day’s work and a space for written comments.',
                padding: 10
            },
            {
                xtype: 'container',
                html: '<b>Time required:</b>It will take approximately 5 minutes to answer preliminary questions  including your typical start and stop times, and then up to 30 to 60 seconds to provide each   report on your mobile device, which you’ll do several times (up to 8) a day. We plan three   sampling periods across Spring 2014 running two to four weeks. There will be a 2-question   follow up survey at the end of each sampling period.',
                padding: 10
            },
            {
                xtype: 'container'
            },
            {
                xtype: 'container',
                html: '<b>Benefits:</b>You will receive an analysis of the empirically sampled data on your own work- related activities. The information that you provide may help us to better understand   faculty workload at the university and the factors that relate to faculty productivity.',
                padding: 10
            },
            {
                xtype: 'container',
                html: '<b>Risks:</b> No risks are anticipated. The information you provide will be anonymous and  confidential. <b>No personally identifying information on your work activities will be provided to your employer.</b> Your decision to participate in this research or the results of   your participation will have no effect on performance evaluations, promotion and tenure   decisions, or any other professional development decisions.',
                padding: 10
            },
            {
                xtype: 'container',
                html: '<b>Confidentiality:</b>Your participation in this research will remain confidential, and the only  identifying information collected will be your email address and your mobile telephone   number. IP addresses are routinely recorded but will also remain completely confidential.   Your contact information will never be shared with anyone. All data exchanged with this   site is protected by SSL encryption.',
                padding: 10
            },
            {
                xtype: 'container',
                html: '<b>Participation and withdrawal:</b> Your participation in this study is completely voluntary,  and you may withdraw at any time without penalty or loss of benefits to which you are   otherwise entitled. To withdraw from the study, click on the withdraw link given in your   confirmation email. Refusal to participate will involve no penalty or loss of benefits to which   you are otherwise entitled.',
                padding: 10
            },
            {
                xtype: 'container',
                html: '<b>To contact the researcher:</b>  If you have any questions or concerns about participation in this study, you should first talk with the   principle investigator <a href="tel:2084262121">John Ziker (426-2121)</a>.',
                padding: 10
            },
            {
                xtype: 'container',
                html: '<b>Whom to contact about complaints, your rights in this research or for questions, concerns, or suggestions that are not being addressed by the research team, or in case of research-related harm:</b> You may contact the Institutional Review Board, which   is concerned with the protection of volunteers in research projects. You may reach the board office   between 8:00 AM and 5:00 PM, Monday through Friday, by calling <a href="tel:2084265401">(208) 426-5401</a> or by writing:   Institutional Review Board, Office of Research Compliance, Boise State University, 1910 University Dr.,   Boise, ID 83725-1138.',
                padding: 10
            },
            {
                xtype: 'container',
                html: '<b>By tapping “Proceed” I agree that the nature and purpose of this research have been sufficiently   explained and I agree to participate in this research. I understand that I am free to withdraw at any time   without incurring any penalty. I also certify that I am over 18 years of age.</b>',
                padding: '10 10 60 10'
            }
        ]
    }

});