/*
 * File: app/view/ThankYou.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.view.ThankYou', {
    extend: 'Ext.Container',

    config: {
        itemId: 'thankYou',
        padding: 20,
        items: [
            {
                xtype: 'container',
                html: 'TAWKS',
                style: 'font-size: 250%'
            },
            {
                xtype: 'container',
                html: 'Your entry has been submitted. You may now close this window.'
            }
        ]
    }

});