/*
 * File: app/view/TimeOut.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.view.TimeOut', {
    extend: 'Ext.Container',

    config: {
        itemId: 'timeOut',
        padding: 20,
        items: [
            {
                xtype: 'container',
                html: 'TAWKS',
                style: 'font-size: 250%'
            },
            {
                xtype: 'container',
                html: 'You timed out.  You may now close this window.'
            },
            {
                xtype: 'container',
                margin: '10 0 10 0'
            },
            {
                xtype: 'button',
                itemId: 'editSettings',
                ui: 'back',
                text: 'Edit My Settings'
            }
        ]
    }

});