/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
    models: [
        'Function',
        'Activity',
        'SocialItem',
        'Time'
    ],
    stores: [
        'Functions',
        'Activities',
        'Social',
        'Times'
    ],
    views: [
        'Main',
        'Working',
        'Functions',
        'Social',
        'Location',
        'Activities',
        'Start',
        'Login',
        'Register',
        'TimePicker',
        'EndDayQuestion',
        'AddFunction',
        'ThankYou',
        'MyCheckbox'
    ],
    requires: [
        'Ext.MessageBox'
    ],
    controllers: [
        'Register',
        'Login',
        'Main',
        'Start',
        'Working',
        'Functions',
        'Activities',
        'Social',
        'Location',
        'EndDayQuestion',
        'ThankYou'
    ],
    name: 'Tawks',

    launch: function() {

        Ext.create('Tawks.view.Main', {fullscreen: true});
    }

});
