/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
    models: [
        'Function',
        'Activity',
        'SocialItem',
        'Time',
        'User'
    ],
    stores: [
        'Functions',
        'Activities',
        'Social',
        'Times',
        'User'
    ],
    views: [
        'Main',
        'Working',
        'Functions',
        'Social',
        'Location',
        'Activities',
        'Start',
        'Login',
        'Register',
        'TimePicker',
        'EndDayQuestion',
        'AddFunction',
        'ThankYou',
        'Success',
        'Pending',
        'MyPicker'
    ],
    requires: [
        'Ext.MessageBox',
        'Ext.ux.field.DateTimePicker'
    ],
    controllers: [
        'Register',
        'Login',
        'Main',
        'Start',
        'Working',
        'Functions',
        'Activities',
        'Social',
        'Location',
        'EndDayQuestion',
        'ThankYou',
        'Success',
        'Pending'
    ],
    name: 'Tawks',

    launch: function() {

        Ext.create('Tawks.view.Main', {fullscreen: true});
    },

    createPickers: function(day) {
        var pickers = [
        {
            xtype: 'datetimepickerfield',
            name : day+'StartTime',
            itemId: day+'StartTime',
            value: new Date(),
            placeHolder: 'Start Time',
            clearIcon: true,
            dateTimeFormat : 'h:i:A',
            autoSelect: false,
            picker: {
                yearFrom: 1980,
                minuteInterval : 1,
                ampm : true,
                cancelButton: {
                    itemId: 'cancelButton',
                    text: 'Clear',
                    listeners: {
                        tap: function () {
                            Ext.ComponentQuery.query('#'+day+'StartTime')[0].setValue('');
                        }
                    }
                },
                slotOrder: ['hour','minute','ampm']
            }
        },
        {
            xtype: 'datetimepickerfield',
            name : day+'EndTime',
            itemId: day+'EndTime',
            value: new Date(),
            placeHolder: 'End Time',
            clearIcon: true,
            dateTimeFormat : 'h:i:A',
            autoSelect: false,
            picker: {
                yearFrom: 1980,
                minuteInterval : 1,
                ampm : true,
                cancelButton: {
                    itemId: 'cancelButton',
                    text: 'Clear',
                    listeners: {
                        tap: function () {
                            Ext.ComponentQuery.query('#'+day+'EndTime')[0].setValue('');
                        }
                    }
                },
                slotOrder: ['hour','minute','ampm']
            }
        }

        ];

        return pickers;
    }

});
