/*
 * File: app/view/Functions.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.view.Functions', {
    extend: 'Ext.dataview.List',

    config: {
        itemId: 'functions',
        store: 'functions',
        onItemDisclosure: false,
        itemTpl: [
            '<div>{type}</div>'
        ],
        items: [
            {
                xtype: 'container',
                docked: 'top',
                hidden: false,
                html: 'Please classify your activity according to a function.',
                padding: 10,
                style: 'background: #EDEBF1; color: #555; font-size: 0.9em;'
            },
            {
                xtype: 'container',
                docked: 'bottom',
                height: 50,
                hidden: true,
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        itemId: 'customFunction',
                        margin: '10 30 10 30',
                        ui: 'action-round',
                        text: 'Add Custom Function'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onCustomFunctionTap',
                event: 'tap',
                delegate: '#customFunction'
            },
            {
                fn: 'onFunctionsInitialize',
                event: 'initialize'
            }
        ]
    },

    onCustomFunctionTap: function(button, e, eOpts) {
        var main = Ext.getCmp('main'),
            addFunction = Ext.create('Tawks.view.AddFunction');

        main.add(addFunction);
        addFunction.show();
    },

    onFunctionsInitialize: function(component, eOpts) {
        var button = {
            xtype: 'container',
            scrollDock: 'bottom',
            height: 50,
            layout: {
                pack: 'center',
                type: 'hbox'
            },
            items: [
            {
                xtype: 'button',
                itemId: 'customFunction',
                margin: '10 30 10 30',
                ui: 'action-round',
                text: 'Add Custom Function'
            }
            ]
        };

        component.add(button);

    }

});