/*
 * File: app/view/Location.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.view.Location', {
    extend: 'Ext.form.Panel',

    config: {
        itemId: 'location',
        items: [
            {
                xtype: 'fieldset',
                title: 'Where were you doing this activity?',
                items: [
                    {
                        xtype: 'radiofield',
                        itemId: 'onCampus',
                        label: 'On Campus',
                        labelWidth: '80%',
                        name: 'locationChoice',
                        value: 'On Campus'
                    },
                    {
                        xtype: 'radiofield',
                        itemId: 'offCampus',
                        label: 'Off Campus',
                        labelWidth: '80%',
                        name: 'locationChoice',
                        value: 'Off Campus'
                    },
                    {
                        xtype: 'radiofield',
                        itemId: 'atHome',
                        label: 'At Home',
                        labelWidth: '80%',
                        name: 'locationChoice',
                        value: 'At Home'
                    }
                ]
            },
            {
                xtype: 'button',
                disabled: true,
                itemId: 'locationButton',
                margin: '10 30 10 30',
                text: 'Submit'
            }
        ]
    }

});