/*
 * File: app/view/Register.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.view.Register', {
    extend: 'Ext.form.Panel',
    alias: 'widget.register',

    config: {
        itemId: 'register',
        layout: {
            type: 'vbox'
        },
        scrollable: true,
        items: [
            {
                xtype: 'fieldset',
                title: 'Personal Info',
                items: [
                    {
                        xtype: 'emailfield',
                        disabled: true,
                        itemId: 'email',
                        name: 'Email',
                        placeHolder: 'email@example.com',
                        listeners: [
                            {
                                fn: function(component, eOpts) {
                                    var main = Ext.getCmp('main');

                                    component.setValue(main.Email);
                                },
                                event: 'initialize'
                            }
                        ]
                    },
                    {
                        xtype: 'hiddenfield',
                        itemId: 'userName',
                        name: 'UserName',
                        listeners: [
                            {
                                fn: function(component, eOpts) {
                                    var main = Ext.getCmp('main');

                                    component.setValue(main.UserName);
                                },
                                event: 'initialize'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Phone',
                items: [
                    {
                        xtype: 'selectfield',
                        name: 'carrier',
                        placeHolder: 'Select Your Carrier',
                        autoSelect: false,
                        options: [
                            {
                                text: 'Verizon',
                                value: '@vtext.com'
                            },
                            {
                                text: 'AT&T',
                                value: '@txt.att.net'
                            },
                            {
                                text: 'T-Mobile',
                                value: '@tmomail.net'
                            },
                            {
                                text: 'Sprint',
                                value: '@messaging.sprintpcs.com'
                            }
                        ]
                    },
                    {
                        xtype: 'textfield',
                        component: {
                            xtype: 'input',
                            type: 'tel',
                            fastFocus: true
                        },
                        name: 'phone',
                        placeHolder: '10-Digit Phone Number'
                    }
                ]
            },
            {
                xtype: 'container',
                html: 'Please enter your hours of availability below.  Leave start and end times empty on the days you don\'t want to be contacted.',
                margin: '10 0 -15 0',
                padding: 10
            },
            {
                xtype: 'fieldset',
                title: 'Monday',
                items: [
                    {
                        xtype: 'selectfield',
                        itemId: 'mondayStartTime',
                        name: 'mondayStartTime',
                        placeHolder: 'Start Time',
                        readOnly: false,
                        autoSelect: false,
                        store: 'times'
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'mondayEndTime',
                        name: 'mondayEndTime',
                        placeHolder: 'End Time',
                        readOnly: false,
                        autoSelect: false,
                        store: 'times'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Tuesday',
                items: [
                    {
                        xtype: 'selectfield',
                        itemId: 'tuesdayStartTime',
                        name: 'tuesdayStartTime',
                        placeHolder: 'Start Time',
                        readOnly: false,
                        autoSelect: false,
                        store: 'times'
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'tuesdayEndTime',
                        name: 'tuesdayEndTime',
                        placeHolder: 'End Time',
                        readOnly: false,
                        autoSelect: false,
                        store: 'times'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Wednesday',
                items: [
                    {
                        xtype: 'selectfield',
                        itemId: 'wednesdayStartTime',
                        name: 'wednesdayStartTime',
                        placeHolder: 'Start Time',
                        readOnly: false,
                        autoSelect: false,
                        store: 'times'
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'wednesdayEndTime',
                        name: 'wednesdayEndTime',
                        placeHolder: 'End Time',
                        readOnly: false,
                        autoSelect: false,
                        store: 'times'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Thursday',
                items: [
                    {
                        xtype: 'selectfield',
                        itemId: 'thursdayStartTime',
                        name: 'thursdayStartTime',
                        placeHolder: 'Start Time',
                        readOnly: false,
                        autoSelect: false,
                        store: 'times'
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'thursdayEndTime',
                        name: 'thursdayEndTime',
                        placeHolder: 'End Time',
                        readOnly: false,
                        autoSelect: false,
                        store: 'times'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Friday',
                items: [
                    {
                        xtype: 'selectfield',
                        itemId: 'fridayStartTime',
                        name: 'fridayStartTime',
                        placeHolder: 'Start Time',
                        readOnly: false,
                        autoSelect: false,
                        store: 'times'
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'fridayEndTime',
                        name: 'fridayEndTime',
                        placeHolder: 'End Time',
                        readOnly: false,
                        autoSelect: false,
                        store: 'times'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Saturday',
                items: [
                    {
                        xtype: 'selectfield',
                        itemId: 'saturdayStartTime',
                        name: 'saturdayStartTime',
                        placeHolder: 'Start Time',
                        readOnly: false,
                        autoSelect: false,
                        store: 'times'
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'saturdayEndTime',
                        name: 'saturdayEndTime',
                        placeHolder: 'End Time',
                        readOnly: false,
                        autoSelect: false,
                        store: 'times'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Sunday',
                items: [
                    {
                        xtype: 'selectfield',
                        itemId: 'sundayStartTime',
                        name: 'sundayStartTime',
                        placeHolder: 'Start Time',
                        readOnly: false,
                        autoSelect: false,
                        store: 'times'
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'sundayEndTime',
                        name: 'sundayEndTime',
                        placeHolder: 'End Time',
                        readOnly: false,
                        autoSelect: false,
                        store: 'times'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'What time would you like to receive your end <br />of the day question?',
                items: [
                    {
                        xtype: 'selectfield',
                        itemId: 'endDayQuestionTime',
                        name: 'endDayQuestionTime',
                        placeHolder: 'Time',
                        readOnly: false,
                        autoSelect: false,
                        store: 'times'
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'register',
                margin: '10 30 10 30',
                text: 'Register'
            }
        ]
    }

});