/*
 * File: app/view/Working.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.view.Working', {
    extend: 'Ext.form.Panel',
    alias: 'widget.working',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Radio'
    ],

    config: {
        itemId: 'working',
        items: [
            {
                xtype: 'fieldset',
                layout: {
                    align: 'center',
                    type: 'vbox'
                },
                title: 'Are you working?',
                items: [
                    {
                        xtype: 'radiofield',
                        itemId: 'yes',
                        width: '100%',
                        label: 'Yes',
                        name: 'working',
                        value: 'yes'
                    },
                    {
                        xtype: 'radiofield',
                        itemId: 'no',
                        width: '100%',
                        label: 'No',
                        name: 'working',
                        value: 'no'
                    }
                ]
            },
            {
                xtype: 'button',
                disabled: true,
                itemId: 'next',
                margin: '10 30 10 30',
                text: 'Next'
            }
        ]
    }

});