/*
 * File: app/store/Functions.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.store.Functions', {
    extend: 'Ext.data.Store',

    requires: [
        'Tawks.model.Function'
    ],

    config: {
        autoLoad: true,
        model: 'Tawks.model.Function',
        storeId: 'functions',
        listeners: [
            {
                fn: 'onJsonstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonstoreLoad: function(store, records, successful, operation, eOpts) {
        var functions = [
        {
            "type": "Teaching",
            "description": "activities related to the formal instruction of scheduled courses as distinct from mentoring of students outside of courses (including the logistical aspects of running a course and one-on-one instruction, labs, clinicals, teacher observations, etc.)." 
        },
        {
            "type": "Research",
            "description": "activities relating to the production of generalizable knowledge, including primary research, preparation of grant proposals, administration of existing projects, and the writing and dissemination of results."
        },
        {
            "type": "Administrative",
            "description": "activities that are related to roles of responsibility for academic units, programs, and faculty (especially where such a role is compensated either monetarily or through a course release), and self-management in terms of formal interaction with the university bureaucracy (e.g., university/college surveys, accounting forms, HR forms, etc.)."
        },
        {
            "type": "Service",
            "description": "activities that are related to professional, university, or community outreach, including peer/grant reviews, editorial roles, department/college/university governance (especially where such a role is not compensated), and community outreach."
        },

        {
            "type": "Advising",
            "description": "direct support of student matriculation through dispensing of programmatic information (as opposed to formal instruction)."
        },
        {
            "type": "In Transit",
            "description": "any kind of travel during work or for work related purposes (walking to and from class, travel to a conference, travel time for service related activities)."
        },
        {
            "type": "Mentoring",
            "description": "Support of student scholarship outside of a course, including career development, research projects, grad school/career/funding applications, and other professional one-on-one interaction."
        },
        {
            "type": "Professional Development",
            "description": "continuing education, training and skills development, workshops/conferences relating to the above."
        }
        ];

        if (records.length === 0) {
            store.add(functions);
        }
    }

});