/*
 * File: app/controller/Location.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.controller.Location', {
    extend: 'Ext.app.Controller',

    config: {
        routes: {
            'location': 'showLocation'
        },

        control: {
            "radiofield#onCampus": {
                change: 'onOnCampusChange'
            },
            "radiofield#offCampus": {
                change: 'onOffCampusChange'
            },
            "radiofield#atHome": {
                change: 'onAtHomeChange'
            },
            "button#locationButton": {
                tap: 'onLocationButtonTap'
            }
        }
    },

    onOnCampusChange: function(checkboxfield, newValue, oldValue, eOpts) {
        Ext.ComponentQuery.query('#locationButton')[0].setDisabled(false);
        Ext.ComponentQuery.query('#locationButton')[0].setUi('confirm');
    },

    onOffCampusChange: function(checkboxfield, newValue, oldValue, eOpts) {
        Ext.ComponentQuery.query('#locationButton')[0].setDisabled(false);
        Ext.ComponentQuery.query('#locationButton')[0].setUi('confirm');
    },

    onAtHomeChange: function(checkboxfield, newValue, oldValue, eOpts) {
        Ext.ComponentQuery.query('#locationButton')[0].setDisabled(false);
        Ext.ComponentQuery.query('#locationButton')[0].setUi('confirm');
    },

    onLocationButtonTap: function(button, e, eOpts) {
        var form = Ext.ComponentQuery.query('#location')[0],
            main = Ext.getCmp('main'),
            me = this;

        form.setMasked({xtype:'loadmask', Message: 'Sending...'});

        main.location = form.getValues().locationChoice;

        var entry = {
            "working": main.working,
            "activity": main.activity,
            "function": main.functions,
            "social": main.social,
            "location": main.location,
            "id": main.tawksId
        };


        Ext.Ajax.request({
            url: 'https://dev-web.boisestate.edu/tawks/form',
            method: 'POST',
            headers: {
                "Content-Type": "application/json"
            },
            params: Ext.encode(entry),
            success: function(response){
                var text = Ext.decode(response.responseText);
                form.setMasked(false);

                Ext.Msg.alert('TAWKS', text, 
                function(btn, something) {
                    // redirect to a completed page...
                    // no more questions to ask send answer up to server...
                    me.redirectTo('thankYou');

                });
            },
            failure: function(response) {
                console.log(response);
            }    
        });
    },

    showLocation: function() {
        var main = Ext.getCmp('main'),
            view = Ext.create('Tawks.view.Location');

        main.setActiveItem(view);
    }

});