/*
 * File: app/controller/Login.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.controller.Login', {
    extend: 'Ext.app.Controller',

    config: {
        routes: {
            'login': 'showLogin'
        },

        control: {
            "button#loginButton": {
                tap: 'onLoginTap'
            }
        }
    },

    onLoginTap: function(button, e, eOpts) {
        var creds = Ext.ComponentQuery.query('#login')[0].getValues(),
            main = Ext.getCmp('main'),
            form = Ext.ComponentQuery.query('#login')[0],
            me = this;

        form.setMasked({xtype:'loadmask', Message: 'Loading...'});

        //console.log(creds);

        Ext.Ajax.request({
            url: 'https://dev-web.boisestate.edu/tawks/account/login',
            method: 'POST',
            headers: {
                "Content-Type": "application/json"
            },
            params: Ext.encode(creds),
            success: function(response){
                var text = Ext.decode(response.responseText);

                if(text === "Invalid Username/Password") {
                    Ext.ComponentQuery.query('#loginFieldSet')[0].setTitle(text);
                    form.setMasked(false);

                }
                else {

                    if(text.View === 'start') {
                        // user needs to register...
                        console.log(text);
                        main.UserName = text.UserName;
                        main.Email = text.Email;
                        form.setMasked(false);
                        me.redirectTo(text.View);
                    } else {
                        console.log(text);
                        // user already registered ...
                        form.setMasked(false);
                        me.redirectTo(text.View);
                    }
                }
            },
            failure: function(response) {
                console.log('fail');
                console.log(response);
            }
        });
    },

    showLogin: function() {
        var main = Ext.getCmp('main'),
            login = Ext.create('Tawks.view.Login');

        main.setActiveItem(login);
    }

});