/*
 * File: app/controller/Start.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.controller.Start', {
    extend: 'Ext.app.Controller',

    config: {
        routes: {
            'start': 'showStart'
        },

        control: {
            "container#start": {
                activate: 'onStartActivate',
                deactivate: 'onStartDeactivate'
            },
            "button#join": {
                tap: 'onJoinTap'
            }
        }
    },

    onStartActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
        var main = Ext.getCmp('main'),
            bottom = main.getComponent('bottom');

        bottom.show();
    },

    onJoinTap: function(button, e, eOpts) {
        this.redirectTo('register');
    },

    onStartDeactivate: function(oldActiveItem, container, newActiveItem, eOpts) {
        var main = Ext.getCmp('main'),
            bottom = main.getComponent('bottom');

        bottom.hide();
    },

    showStart: function() {
        var main = Ext.getCmp('main'),
            start = Ext.create('Tawks.view.Start');

        main.setActiveItem(start);
    }

});