/*
 * File: app/controller/Working.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.controller.Working', {
    extend: 'Ext.app.Controller',

    config: {
        routes: {
            'working': 'showWorking'
        },

        control: {
            "radiofield#yes": {
                change: 'onYesChange'
            },
            "radiofield#no": {
                change: 'onNoChange'
            },
            "button#next": {
                tap: 'onNextTap'
            }
        }
    },

    onYesChange: function(checkboxfield, newValue, oldValue, eOpts) {
        //Ext.ComponentQuery.query('#next')[0].setDisabled(false);
        //Ext.ComponentQuery.query('#next')[0].setUi('confirm');

        this.userAnswer();
    },

    onNoChange: function(checkboxfield, newValue, oldValue, eOpts) {
        //Ext.ComponentQuery.query('#next')[0].setDisabled(false);
        //Ext.ComponentQuery.query('#next')[0].setUi('confirm');

        this.userAnswer();
    },

    onNextTap: function(button, e, eOpts) {
        var form = Ext.ComponentQuery.query('#working')[0],
            answer = form.getValues(),
            main = Ext.getCmp('main'),
            me = this;



        main.working = answer.working;
        console.log(main.working);

        if(answer.working === 'yes') {

            this.redirectTo('activities');

        } else {


            var entry = { working: main.working };

            form.setMasked({xtype: 'loadmask', Message:'Sending...'});

            /*
            Ext.Ajax.request({
            url: 'https://dev-web.boisestate.edu/tawks/form',
            method: 'POST',
            headers: {
            "Content-Type": "application/json"
            },
            params: Ext.encode(entry),
            success: function(response){
            var text = Ext.decode(response.responseText);
            form.setMasked(false);

            Ext.Msg.alert('TAWKS', 'Thank You. This entry has been coded as personal time.', 
            function(btn, something) {

            me.redirectTo('thankYou');

            }
            );
            },
            failure: function(response) {
            console.log(response);
            }    
            });
            */
            Ext.Msg.alert('TAWKS', 'Thank You. This entry has been coded as personal time.', 
            function(btn, something) {

                me.redirectTo('thankYou');

            }
            );

        }
    },

    showWorking: function() {
        var main = Ext.getCmp('main'),
            view = Ext.create('Tawks.view.Working');


        main.query('#backButton')[0].hide();
        main.setActiveItem(view);
    },

    userAnswer: function() {
        var form = Ext.ComponentQuery.query('#working')[0],
            answer = form.getValues(),
            main = Ext.getCmp('main'),
            me = this;



        main.working = answer.working;
        //console.log(main.working);

        if(answer.working === 'true') {

            this.redirectTo('activities');

        } else {


            var entry = { working: main.working, id: main.tawksId };

            form.setMasked({xtype: 'loadmask', Message:'Sending...'});


            Ext.Ajax.request({
                url: 'https://dev-web.boisestate.edu/tawks/form',
                method: 'POST',
                headers: {
                    "Content-Type": "application/json"
                },
                params: Ext.encode(entry),
                success: function(response){
                    var text = Ext.decode(response.responseText);
                    form.setMasked(false);

                    Ext.Msg.alert('TAWKS', text, 
                    function(btn, something) {

                        me.redirectTo('thankYou');

                    }
                    );
                },
                failure: function(response) {
                    console.log(response);
                }    
            });

        }
    }

});