/*
 * File: app/controller/Register.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.controller.Register', {
    extend: 'Ext.app.Controller',

    config: {
        routes: {
            'register': 'showRegister'
        },

        control: {
            "textfield#mondayStartTime": {
                focus: 'onMondayStartTimeFocus'
            },
            "textfield#mondayEndTime": {
                focus: 'onMondayEndTimeFocus'
            },
            "button#register": {
                tap: 'onRegisterTap'
            }
        }
    },

    onMondayStartTimeFocus: function(textfield, e, eOpts) {
        //this.showPicker(textfield);
    },

    onMondayEndTimeFocus: function(textfield, e, eOpts) {
        //this.showPicker(textfield);
    },

    onRegisterTap: function(button, e, eOpts) {
        var main = Ext.getCmp('main'),
            register = main.getComponent('register');

        console.log(register.getValues());

        Ext.Ajax.request({
            url: 'https://dev-web.boisestate.edu/tawks/account/register',
            method: 'POST',
            headers: {
                "Content-Type": "application/json"
            },
            params: Ext.encode(register.getValues()),
            success: function(response){
                var text = Ext.decode(response.responseText);


                console.log(text);

                //me.redirectTo('start');
            },
            failure: function(response) {
                console.log(response);
            }    
        });
    },

    showRegister: function() {
        var main = Ext.getCmp('main'),
            register = Ext.create('Tawks.view.Register');

        main.setActiveItem(register);
    },

    showPicker: function(textfield) {
        var timePicker = Ext.ComponentQuery.query('#timePicker')[0] || Ext.create('Tawks.view.TimePicker');

        timePicker.show();
        timePicker.form = textfield;
    }

});