/*
 * File: app/controller/Working.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tawks.controller.Working', {
    extend: 'Ext.app.Controller',

    config: {
        routes: {
            'working': 'showWorking'
        },

        control: {
            "radiofield#yes": {
                change: 'onYesChange'
            },
            "radiofield#no": {
                change: 'onNoChange'
            },
            "button#next": {
                tap: 'onNextTap'
            }
        }
    },

    onYesChange: function(checkboxfield, newValue, oldValue, eOpts) {
        Ext.ComponentQuery.query('#next')[0].setDisabled(false);
        Ext.ComponentQuery.query('#next')[0].setUi('confirm');
    },

    onNoChange: function(checkboxfield, newValue, oldValue, eOpts) {
        Ext.ComponentQuery.query('#next')[0].setDisabled(false);
        Ext.ComponentQuery.query('#next')[0].setUi('confirm');
    },

    onNextTap: function(button, e, eOpts) {
        var answer = Ext.ComponentQuery.query('#working')[0].getValues(),
            main = Ext.getCmp('main');



        main.working = answer.working;
        console.log(main.working);

        if(answer.working === 'yes') {

            this.redirectTo('activities');

        } else {

            Ext.Msg.alert('TAWKS', 'Thank You. This entry as been coded as personal time.', 
            function(btn, something) {
                // redirect to a completed page...
                // no more questions to ask send answer up to server...

            });
        }
    },

    showWorking: function() {
        var main = Ext.getCmp('main'),
            view = Ext.create('Tawks.view.Working');

        main.setActiveItem(view);
    }

});